version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - ./.env:/app/.env
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_URL: mongodb://db:27017/?compressors=disabled&gssapiServiceName=mongodb
      DB_NAME: calculator
      PORT: 3001
  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo/storage:/data/db
    environment:
      - MONGO_INITDB_DATABASE=calculator
    ports:
      - 27017:27017
